#!/usr/bin/env node
/**
 * build-index.mjs — إعادة توليد فهرس الأعضاء والنسخة المدمجة
 * ------------------------------------------------------------------
 * الاستخدام / Usage:
 *     node tools/build-index.mjs            # توليد فقط / just build
 *     node tools/build-index.mjs --check    # فشل إذا كان الفهرس قديماً (لـ CI)
 *
 * المخرجات / Outputs:
 *     data/members-index.json   فهرس أسماء ملفات البطاقات
 *     data/members-bundle.js    نسخة مدمجة تعمل بدون خادم (file://)
 *
 * ملاحظة: هذا الملف هو الحل النهائي لتعارض ملف الفهرس — لا تحلّ التعارض يدوياً.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MEMBERS_DIR = path.join(ROOT, "data", "members");
const INDEX_FILE = path.join(ROOT, "data", "members-index.json");
const BUNDLE_FILE = path.join(ROOT, "data", "members-bundle.js");
const CONFIG_FILE = path.join(ROOT, "data", "site-config.json");

const isCard = (f) => f.endsWith(".json") && !f.startsWith("00-") && !f.startsWith("_");

async function readJSON(file, fallback = null) {
  try {
    return JSON.parse(await readFile(file, "utf8"));
  } catch {
    return fallback;
  }
}

async function main() {
  const checkMode = process.argv.includes("--check");

  const entries = (await readdir(MEMBERS_DIR)).filter(isCard).sort();
  const members = [];
  for (const file of entries) {
    const card = await readJSON(path.join(MEMBERS_DIR, file));
    if (card) members.push({ file, ...card });
  }
  members.sort((a, b) => String(a.github).localeCompare(String(b.github)));

  const index = {
    _comment: "فهرس ملفات البطاقات — ملف مُولَّد، لا تعدّله يدوياً.",
    _generated: true,
    total: entries.length,
    files: entries,
  };

  const config = (await readJSON(CONFIG_FILE)) ?? {};
  const banner =
    "/* ملف مُولَّد تلقائياً — لا تعدّله يدوياً. Generated by tools/build-index.mjs */\n";
  const bundle =
    banner +
    "window.MEMBERS_DATA = " +
    JSON.stringify(
      {
        config,
        members: members.map(({ file, ...rest }) => ({ file, ...rest })),
      },
      null,
      2
    ) +
    ";\n";

  const prevIndex = await readFile(INDEX_FILE, "utf8").catch(() => "");
  const prevBundle = await readFile(BUNDLE_FILE, "utf8").catch(() => "");
  const nextIndex = JSON.stringify(index, null, 2) + "\n";

  if (checkMode) {
    const stale = prevIndex !== nextIndex || prevBundle !== bundle;
    if (stale) {
      console.error("[build-index] ✘ الفهرس غير محدَّث. شغّل: node tools/build-index.mjs");
      process.exit(1);
    }
    console.log("[build-index] ✔ الفهرس محدَّث بالفعل.");
    return;
  }

  await writeFile(INDEX_FILE, nextIndex, "utf8");
  await writeFile(BUNDLE_FILE, bundle, "utf8");
  console.log(`[build-index] ✔ تم توليد الفهرس: ${entries.length} بطاقة.`);
  members.forEach((m) => console.log(`   • ${m.github.padEnd(22)} ${m.role}`));
}

main().catch((err) => {
  console.error("[build-index] ✘ خطأ:", err.message);
  process.exit(1);
});
