'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Class ClassesPage
    Inherits System.Web.UI.Page

    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtGrade As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtRoom As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvClasses As Global.System.Web.UI.WebControls.GridView
End Class
