'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Class SiteMaster
    Inherits System.Web.UI.MasterPage

    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
