'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Class StudentsPage
    Inherits System.Web.UI.Page

    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    Protected WithEvents txtFullName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents valFullName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlClass As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlFilterClass As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    Protected WithEvents gvStudents As Global.System.Web.UI.WebControls.GridView
End Class
